# vector lab

In [2]:
import numpy as np


In [5]:
u= np.array([3,4])
v= np.array([6,8])
print(np.linalg.norm(u))
np.linalg.norm(v)


5.0


10.0

In [11]:
b= np.array([[1,2,3,0],[2,4,3,2]])
print(b)

[[1 2 3 0]
 [2 4 3 2]]


In [22]:
c= np.array([[2,1,-1], [0,3,-2],[2,4,-3]])
print(c)
c.transpose()

[[ 2  1 -1]
 [ 0  3 -2]
 [ 2  4 -3]]


array([[ 2,  0,  2],
       [ 1,  3,  4],
       [-1, -2, -3]])

In [23]:
np.linalg.matrix_rank(c)

2

In [24]:
import math

In [25]:
def geometric(x, y, theta):
    x_norm= np.linalg.norm(x)
    y_norm= np.linalg.norm(y)
    return x_norm*y_norm* math.cos(math.radians(theta))


In [36]:
theta= 60
x= [3,4]
y=[6,8]
geometric(x,y, theta)

25.000000000000007